sudo pmset -a lidwake 1
sudo pmset -a autopoweroff 1
sudo pmset -a autopoweroffdelay 10800
sudo pmset -a standbydelay 3600
sudo pmset -a standby 1
sudo pmset -a ttyskeepawake 0
sudo pmset -a hibernatemode 25
sudo pmset -a powernap 0
sudo pmset -b displaysleep 3
sudo pmset -c displaysleep 5
sudo pmset -c womp 0
sudo pmset -c networkoversleep 0
sudo pmset -b sleep 5
sudo pmset -c sleep 10
sudo pmset -a acwake 0
sudo pmset -a halfdim 1
sudo pmset -b lessbright 1
sudo pmset -a disksleep 10
